language: python

os:
  - linux

dist: trusty
sudo: enabled

python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - language: generic
      python: 3.6
      os: osx
      before_install:
        # brew install below does auto-update first which adds ~2 min.
        # HOMEBREW_AUTO_UPDATE_SECS or HOMEBREW_NO_AUTO_UPDATE might help
        - brew install python3 yaz
        - virtualenv ~/env -p python3
        - source ~/env/bin/activate
        - pip install pytest

addons:
  apt:
    sources:
    - sourceline: 'deb http://ftp.indexdata.dk/ubuntu trusty main'
      key_url: http://ftp.indexdata.dk/debian/indexdata.asc
    packages:
    - yaz

before_install:
  - yaz-marcdump -V

install: pip install -r requirements.txt

before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

script: pytest
